[package]
name = "psamlearn"
version = "0.1.0"
authors = ["Bart Massey <bart.massey@gmail.com>"]
edition = "2018"

[dependencies]
argh = "0.1"
bit-vec = "0.6"
csv = "1.1"
rand = "0.7"

[dependencies.serde]
version = "1"
features = ["derive"]
